# Generated by Django 4.2.7 on 2023-11-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_avatar_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('educator', 'educator'), ('moderator', 'moderator')], default='educator', max_length=10),
        ),
    ]
